baseURL = "/"
title = "Macrowise"
publishDir = "docs"
disqusShortname = "macrowise"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
	[[params.brands]]
		name = "twitter"
		url = "https://twitter.com/WiseMacro"
	[[params.brands]]
		name = "medium-m"
		url = "https://medium.com/@contentmanagermw"